#
# kernel/ve/vznetstat/Makefile
#
# Copyright (c) 2005-2008 SWsoft
# Copyright (c) 2009-2015 Parallels IP Holdings GmbH
# Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
#

obj-$(CONFIG_VE_NETDEV_ACCOUNTING) += vznetstat.o ip_vznetstat.o ip6_vznetstat.o
