# Intel pin control drivers

obj-$(CONFIG_PINCTRL_BAYTRAIL)		+= pinctrl-baytrail.o
obj-$(CONFIG_PINCTRL_INTEL)		+= pinctrl-intel.o
obj-$(CONFIG_PINCTRL_CANNONLAKE)	+= pinctrl-cannonlake.o
obj-$(CONFIG_PINCTRL_CEDARFORK)		+= pinctrl-cedarfork.o
obj-$(CONFIG_PINCTRL_DENVERTON)		+= pinctrl-denverton.o
obj-$(CONFIG_PINCTRL_GEMINILAKE)	+= pinctrl-geminilake.o
obj-$(CONFIG_PINCTRL_ICELAKE)		+= pinctrl-icelake.o
obj-$(CONFIG_PINCTRL_LEWISBURG)		+= pinctrl-lewisburg.o
obj-$(CONFIG_PINCTRL_BROXTON)		+= pinctrl-broxton.o
obj-$(CONFIG_PINCTRL_SUNRISEPOINT)	+= pinctrl-sunrisepoint.o
