This is a dummy spec file.  It will be replaced by the sources target of the
Makefile in this directory.  That target will replace this file with the real
kernel.spec file in ../rpm/SPECS as generated by make -C ../ rh-sources

