fullbuild:
	go build RHMAINTAINERS_parser.go
	go build yaml2RHMAINTAINERS.go
	go build yaml2CODEOWNERS.go
	go build verifySubsystems.go validSSTNames.go
	go build searchowners.go

clean:
	rm -f RHMAINTAINERS_parser yaml2RHMAINTAINERS yaml2CODEOWNERS verifySubsystems searchowners

