---
title: 'Red Hat Commit Attribution Policy'
date: 2021-07-20T19:30:08+10:00
draft: false
weight: 2
summary: Red Hat requires that all commits must be attributed to the contributor of the Merge Request in the case of a backported commit from upstream or a RHEL specific commit.
---

= Red Hat Commit Attribution Policy

Red Hat requires that all commits must be attributed to the contributor of the Merge Request in the case of a backported commit from upstream or a RHEL specific commit.

== Backported Commits

In cases where the upstream commit author is not the Red Hat contributor, the Red Hat contributor must be listed as the Red Hat commit author.  In the example below the Red Hat Git Repository Author, or the Merge Request Contributor, is ‘+Prarit Bhargava <prarit@redhat.com>+’, and the upstream commit author, or the Upstream Contributor, is ‘+Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>+’.

----
commit b97a3956576a2f97bbb3c7205214919d743f4b41
Author: Prarit Bhargava <prarit@redhat.com>
Date:   Tue Dec 1 18:36:50 2020 -0500

	[tools] tools/power/x86/intel-speed-select: Update version for v5.10

	Bugzilla: http://bugzilla.redhat.com/1896211

	commit e529412f3211071b4787a8e7e153c8ced3c22a28
	Author: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
	Date:   Tue Oct 6 06:26:31 2020 -0700

		tools/power/x86/intel-speed-select: Update version for v5.10

		Update version for changes released with v5.10 kernel release.

		Signed-off-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
		Signed-off-by: Hans de Goede <hdegoede@redhat.com>

	Signed-off-by: Prarit Bhargava <prarit@redhat.com>
	Signed-off-by: Jan Stancek <jstancek@redhat.com>
----

== RHEL Specific Patches

Patches unique to Red Hat repositories must be attributed to the author of the Merge Request.

== Tips and Tricks for Attributing commits

* If using https://gitlab.com/redhat/centos-stream/src/kernel/utils/tools/-/blob/main/git-backport[git-backport] and https://git-scm.com/docs/git-commit[git-commit] to apply backported commits, there is no need for further action.  git-backport correctly adds a “From:” line to all backported commits and can be applied using git-commit.
* If using https://git-scm.com/docs/git-cherry-pick[git-cherry-pick] and https://git-scm.com/docs/git-commit[git-commit] to apply backported commits, the commits can be correctly attributed by using git-commit’s --reset-author option, or, by adding a +“From: FirstName LastName <user@redhat.com>”+ line to the first line of the backported commits.
