---
title: 'Create a Merge Request for z-stream'
date: 2021-07-20T19:30:08+10:00
draft: false
weight: 3
summary: instructions for creating a MR for z-stream.
---
= Create a Merge Request for z-stream


Merge requests for z-stream can be created by following instructions for creating a merge request against a specific branch.

Merge Requests against a specific branch can be created by doing

----
	git checkout <target branch name> # ie) 8.2 for example
	git checkout -b <local_branch_name>
----

and making changes on local_branch_name.  *Before modifying code users should read* link:CommitRules.adoc[*CommitRules*] *and* link:verifying_a_gitlab_MR.adoc[*verify the MR information*].

Merge requests can be created by pushing code to their fork and targeting <target_branch_name>

----
	git push -u <fork_name> <branch_name>
	lab mr create --remove-source-branch <origin> <target branch name>
----

The last command will output the Merge Request URL that contains the Merge Request ID.

_It is strongly recommended lab users use the _lab mr create --draft option_ to pass the webhook checks, and when successful, remove the Draft status on the MR with

----
	lab mr edit <mrID> --ready
----

== Troubleshooting


.  I made a mistake and forgot to specify the target_branch_name ie) I executed lab mr create  <origin> instead of lab mr create  <origin> <target branch name>.  How do I clean this up?

This is easy to fix.  Simply execute

----
	lab mr edit <mrID> --target-branch <target_branch_name>
----
