---
title: 'Email-based patch vs GitLab Merge Request'
date: 2021-07-20T19:30:08+10:00
draft: false
weight: 3
summary: How to migrate from an email-based workflow to GitLab.
---

= Kernel Workflow: Email-based patch vs GitLab Merge Request

Red Hat Kernel Development is moving from an email-based workflow to using a git-forge workflow based on GitLab.  There are two phases of the move that affect Engineers; the first phase requires all engineers to submit changesets through GitLab, and the second phase requires engineers to review changesets in GitLab.  The instructions and examples below provide engineers with examples of how to migrate their email-based workflows to GitLab.

== Scope

The instructions below assume knowledge of Red Hat’s development process, and familiarity with git and GitLab.

Some users employ tools such as quilt or guilt to submit patches to mailto:rhkernel-list@redhat.com[rhkernel-list@redhat.com].  It is beyond the scope of this document to list every possible kernel development tool example, and describe differences between those tools and the GitLab process.

== Differences in git commit rules

The email-based patch workflow supported the commit format generated by git-cherry-pick with minor changes. The new rules have additional differences and require additional tweaking before pushing commits:

* Commit author information is expected to contain the person responsible for the backport, not the upstream commit author. Contributors using git-cherry-pick need to use git-commit’s --reset-author option.
* Upstream contributors Cc’s, Signed-off-by:, and other tags must be shifted right by 4 spaces to avoid the email bridge from erroneously cc’ing non-redhat.com email addresses.
== Submitting Patches to Gitlab

The current RHEL kernel development workflow uses email to submit patches for review.  To submit patches, in general, engineers are executing commands similar to

	git checkout -b <branch_name>
	git-backport or git-cherry-pick # apply backport patches to RHEL git tree
	# test
	git-format-patch -n <number_of_patches> -o <patchset_location> --cover-letter
	git-send-email --to=rhkernel-list@redhat.com <patchset_location>

In the new RHEL kernel development workflow uses git & GitLab to submit patches for review, and developers will now do,

	git checkout -b <branch_name>
	git-backport or git-cherry-pick # apply backport patches to RHEL git tree
	# test
	git push <repo_remote_name> <branch_name>
	lab mr create --remove-source-branch <branch_name> --cover-letter --force-linebreak

The last command ‘lab mr create <branch_name>’, will open a $GIT_EDITOR window in which a cover-letter can be created.  Saving and exiting the editor results in a Red Hat tool called the ‘GitLab Email Bridge’ sending patch emails to mailto:rhkernel-list@redhat.com[rhkernel-list@redhat.com] so that engineers can review the submitted patches, and maintainers can process and apply the reviewed patches.

== Why is the --cover-letter output different?

Users will note that there is a difference between the cover-letter output provided by ‘git-format-patch’ and ‘lab mr create’.

For example, git-format-patch provides a changelog of

	Prarit Bhargava (3):
	Prarit's USB Change
	Prarit’s PCI Change
	Prarit’s x86 Change

And ‘lab mr create’ provides a slightly different format for the changelog of

	51ef9fdd2980 (Prarit Bhargava)
	   Prarit's USB Change

	418efa98c02 (Prarit Bhargava)
	   Prarit's PCI Change

	39adce45218 (Prarit Bhargava)
	   Prarit's x86 Change

The reason for the difference is that in GitLab the commit IDs are static and can be referenced by reviewers in an updated git tree.  For example, if a reviewer was only interested in the PCI change above, they could do,

	git fetch origin
	lab mr checkout <merge_request_id>
	git show 418efa98c02

to view the PCI change.

== Changesets requiring review

To obtain the list of outstanding changesets, users can use the GitLab WebUI, xref:revumatic.adoc[revumatic], https://gitlab.com/prarit/rhstatus[rhstatus] or, using xref:lab.adoc[lab], execute

	git fetch upstream
	lab mr list
	# lab mr list defaults to a list of 10 and can be overridden with --all or -n <number>

== Retrieving patches on the command line

The GitLab Merge Request model allows reviewers to obtain patches on the command line instead of copying patches from a mail reader, or downloading an mbox that contains the patches.

Open Merge Requests can be retrieved by executing

	‘lab mr list’

A specific MR can be checked out by

	lab mr checkout <merge_request_id>

And the patches can be generated by executing

	git-format-patch -n <number of patches>

The patches can be exported to a mbox file with the ‘--stdout’ argument to ‘git-format-patch’.

== lab config files

The xref:lab.adoc[lab] utility has config files that allow for per-instruction configuration.  For example,

	lab mr create <branch_name> --cover-letter --force-linebreak --remove-source-branch

Can be shortened to ‘lab mr create <branch_name>’ by adding

	[mr_create]
	 cover-letter = true
	 force-linebreak = true
         remove-source-branch = true

to the local .git/lab/lab.toml file.

Another example, lab mr show <mr_id>’ will always show comments, if

	[mr_show]
	 Comments = true

to the local .git/lab/lab.toml file.

== Reviewing Changesets

Changesets are posted to mailto:rhkernel-list@redhat.com[rhkernel-list@redhat.com] and can be reviewed using the existing email review policies.

== Notifications

While email is no longer used to submit patchsets, email is still used to inform developers about changesets they are or may be interested in.  Information on the different types of notifications can be found link:kernel_changeset_notifications.adoc[here].

