---
title: 'Kernel Git Repository Information'
date: 2021-07-20T19:30:08+10:00
draft: false
weight: 2
summary: Git repository information.
---

{{< toc >}}

There are many source-git and dist-git repositories that are used to construct Red Hat kernels.  Some of these repositories are used for testing (CKI), but most of these repositories are used for code that is shipped to customers.   Red Hat kernel git repositories use ‘main’ in place of git’s default ‘master’ branch.

== source-git repositories

Public git repositories can be used by Red Hat contributors, Community Contributors, and all Partner Engineer contributors.  Private git repositories are restricted to Red Hat contributors and Partner contributors.

The general model of these repositories is that the main branch tracks the current minor development, and other branches track old minor development (commonly referred to as ‘z-stream’).  Some repositories may also contain Real Time kernel branches that are tagged with “-rt”.

For example, the rhel-8 repository contains branches and the main branch (as of writing this section) is for 8.5 development

  remotes/origin/8.0 +
  remotes/origin/8.1 +
  remotes/origin/8.2 +
  remotes/origin/8.2-rt +
  remotes/origin/8.3 +
  remotes/origin/8.3-rt +
  remotes/origin/8.4 +
  remotes/origin/8.4-rt +
  remotes/origin/HEAD -> origin/main +
  remotes/origin/main +
  remotes/origin/main-rt


=== Public

https://gitlab.com/redhat/centos-stream/src/kernel/documentation[Documentation on RHEL, Fedora, and CentOS kernel workflow]

https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-8[CentOS-Stream 8 kernel]
for future RHEL8 development

https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9[CentOS-Stream 9 kernel]
for general and future RHEL9 development

https://gitlab.com/cki-project/kernel-ark.git[Fedora/ARK] and
https://cki-project.gitlab.io/kernel-ark/[Fedora/ARK kernel documentation]

https://gitlab.com/redhat/centos-stream/src/kernel/utils/tools[Kernel tools] &ndash;
a collection of useful tools and scripts including
https://gitlab.com/redhat/centos-stream/src/kernel/utils/tools/-/blob/main/git-backport[git-backport] tool


=== Private

Private repositories contain Red Hat private information and partner data
and are restricted to Red Hat employees only.
These repositories will never be made public.

https://gitlab.com/redhat/rhel/src/kernel/rhel-8-sandbox[RHEL-8 sandbox],
https://gitlab.com/redhat/rhel/src/kernel/rhel-9-sandbox[RHEL-9 sandbox]
&ndash; to test webhooks, internal scripts, user process, user’s scripts, etc.

https://gitlab.com/redhat/rhel/src/kernel/rhel-8[RHEL-8] &ndash;
private, but various sanitized versions exist through CentOS-Stream or the partner program.

https://gitlab.com/redhat/rhel/src/kernel/rhel-9[RHEL-9] &ndash;
Future tree for RHEL-9 development.
See CentOS-Stream for tree location for main development.
The CentOS-Stream 9 repository should be used for general development.
The RHEL-9 tree only contains z-stream branches.

https://gitlab.com/redhat/rhel/src/kernel/rhel-5[RHEL-5],
https://gitlab.com/redhat/rhel/src/kernel/rhel-6[RHEL-6],
https://gitlab.com/redhat/rhel/src/kernel/rhel-7[RHEL-7]

https://gitlab.com/redhat/rhel/src/kernel/rhel-alt-7[RHEL-alt-7]
&ndash; archived project.

Embargoed &ndash; with additional restricted access.
In some cases, these are Red Hat internal only.
Used to resolve CVE and other partner-related embargoed issues.


== dist-git repositories

Public git repositories can be used by Red Hat contributors, Community Contributors, and all Partner Engineer contributors.  Private git repositories are restricted to Red Hat contributors and Partner contributors.

|===
|Name|Location|Type

|CentOS-Stream|TBD|Public
|RHEL-8|pkgs.devel.redhat.com TBD|Private (internal)
|RHEL-9|pkgs.devel.redhat.com TBD|Private (internal)
|CentOS (public)|TBD|TBD (The public CentOS-Stream tree is mirrored to both the private Red Hat and public CentOS dist-git trees.)
|CentOS (private)|TBD|TBD (The public CentOS-Stream tree is mirrored to both the private Red Hat and public CentOS dist-git trees.)
|===

== CI repositories

The kernel workflow relies heavily on CI automation which is implemented in various repositories under the CKI namespace.
|===
|Name|Type|Description

|https://gitlab.com/cki-project[CKI]|public|All CKI code repositories
|https://gitlab.com/cki-project/pipeline-definition[Main pipeline implementation]|public|Main repository of the CKI pipeline implementation. When in doubt, use this to report issues.
|https://gitlab.com/redhat/red-hat-ci-tools/kernel[Pipeline runs]|public group, specific projects restricted|Pipeline runs and logs. People don't need to access the projects directly but through merge request links unless setting things up.
|===

== DataWarehouse

DataWarehouse is the CKI database and dashboard. It includes build and test information for all non-embargoed CKI runs. Data for public kernels (upstream, CentOS Stream) is publicly readable, access to RHEL kernel data requires sign in with Red Hat SSO.

|===
|Name|Type|Description

|https://datawarehouse.cki-project.org[DataWarehouse]|Public|CKI database and dashboard.
|===

