---
title: 'General Build Instructions'
weight: 2
summary: Entry point.
---
= RHEL Kernel Build Instructions

Simple instructions for building RHEL and CentOS-Stream kernels.

== RHEL & CentOS Stream Repository Layout

CentOS Stream repositories' main branch point to the current development tree (aka latest or the next release).  RHEL repositories' main branch mirror the CentOS Stream main branch.  In both repositories, previous releases are self-named; for example, the rhel-8 branch for 8.2 is named remotes/origin/8.2.

Contributions to RHEL must be made via the CentOS Stream main branch.  Merge Requests against RHEL's main branch will be ignored and eventually rejected.

== Local build instructions

Local builds may require additional packages to be installed.   A Red Hat or CentOS-Stream specific .config can be obtained by executing:

----
git clone <kernel repository>; cd <kernel repository> +
make dist-configs # or make dist-configs-arch  +
cp redhat/configs/<version-arch>.config .config
----

Older RHEL repositories may use rh-* in place of dist-* in make commands.

== Brew build instructions

In general, users can submit an MR and use the CKI build artifacts.  In cases where a brew build is required, a build for all supported architectures can be completed by executing

----
make dist-brew
----

Specific architectures can be built by setting the BUILD_FLAGS variable.  For example, to build the x86_64 and noarch architectures,

----
make dist-brew BUILD_FLAGS="--arch-override=x86_64,noarch"
----

== Command Help

Help for additional RHEL make commands can be viewed by executing “make dist-help”.
