---
title: 'General Build Instructions'
weight: 2
summary: Entry point.
---
= RHEL Kernel Build Instructions

Simple instructions for building RHEL and CentOS-Stream kernels.

== RHEL & CentOS Stream Repository Layout

CentOS Stream repositories' main branch point to the current development tree (aka latest or the next release).  RHEL repositories' main branch mirror the CentOS Stream main branch.  In both repositories, previous releases are self-named; for example, the rhel-8 branch for 8.2 is named remotes/origin/8.2.

Contributions to RHEL must be made via the CentOS Stream main branch.  Merge Requests against RHEL's main branch will be ignored and eventually rejected.

== Local build instructions

Local builds may require additional packages to be installed.   A Red Hat or CentOS-Stream specific .config can be obtained by executing:

----
git clone <kernel repository>; cd <kernel repository> +
make dist-configs # or make dist-configs-arch  +
cp redhat/configs/<version-arch>.config .config
----

Older RHEL repositories may use rh-* in place of dist-* in make commands.

== Command Help

Help for additional RHEL make commands can be viewed by executing “make dist-help”.
