obj-y			+= core.o

obj-$(CONFIG_CPU_SUP_AMD)               += amd/core.o amd/uncore.o
obj-$(CONFIG_X86_LOCAL_APIC)            += amd/ibs.o msr.o

obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/

obj-$(CONFIG_CPU_SUP_INTEL)		+= msr.o
