obj-y			+= core.o

obj-$(CONFIG_CPU_SUP_AMD)               += amd/core.o amd/uncore.o
obj-$(CONFIG_X86_LOCAL_APIC)            += amd/ibs.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/core.o intel/bts.o intel/cqm.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/ds.o intel/knc.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/lbr.o intel/p4.o intel/p6.o intel/pt.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/rapl.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/uncore.o intel/uncore_nhmex.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/uncore_snb.o intel/uncore_snbep.o
