#
# kernel/ve/dummy/Makefile
#
# Copyright (c) 2000-2008 SWsoft
# Copyright (c) 2009-2015 Parallels IP Holdings GmbH
# Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
#

obj-m += ip6_vzprivnet.o
obj-m += ip_vzprivnet.o
obj-m += pio_nfs.o
