#
# User resources part (UBC)
#
# Copyright (c) 2005-2008 SWsoft
# Copyright (c) 2009-2015 Parallels IP Holdings GmbH
# Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
#

obj-y := sys.o beancounter.o misc.o \
	 vm_pages.o statd.o

obj-$(CONFIG_BC_PROC)  += proc.o
obj-$(CONFIG_BC_IO_ACCOUNTING) += io_acct.o
obj-$(CONFIG_BC_IO_PRIORITY) += io_prio.o
